### PR TITLE
REP-4296 Add a `--configFile` parameter.

### PR DESCRIPTION
**Pull request by FGasper**
This allows users to specify the verifier’s configuration via a configuration file rather than CLI parameters.

### CODE REVIEW

**Comment by tfogo** [comment]
What's the behavior if you specify an option in the file and on the command line?

**Comment by FGasper** [comment]
@tfogo What I saw is that it amalgamates them both. I don‘t know if we want to specify that behavior, though.

**Review by mmcclimon — APPROVED** [review]
LGTM!

**Comment by tfogo** [comment]
Hmmm... it's probably fine, whichever way it works tbh.

**Review by tfogo — APPROVED** [review]
LGTM

**Review by tdq45gj — APPROVED** [review]
LGTM!

**Pull request merged**
